### ISSUE TITLE
Support for gpodder2go

### ISSUE THREAD

**Issue by update-freak** [Heckie75/kodi-addon-podcast#27]
The sync with gpodder2go (https://github.com/oxtyped/gpodder2go) does not work with this addon.
I openend the Addon in Kodi but got no items (only the back-dots are visible),
Not sure if the support for gpodder2go is missing or if it's a bug (In the Addon I selected the gpodder service).
Below you will find the docker compose for gpodder2go (source: https://github.com/oxtyped/gpodder2go/pull/44)

```
services:
  gpodder2go:
    image: quay.io/mhrivnak/gpodder2go-container:mhrivnak-fork
    container_name: gpodder2go
    ports:
      - 3005:3005
    environment:
      - NO_AUTH=false
      - VERIFIER_SECRET_KEY=""
    volumes:
      - /volume1/docker/gpodder2go:/data
    restart: unless-stopped
```
